---
- name: setup jenkins slave 
  become: true
  hosts: jenkins-slave
  tasks:
    - name: install java 21 
      yum: 
        name: java-21-amazon-corretto
        state: present
    
    - name: download maven package
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.12/binaries/apache-maven-3.9.12-bin.tar.gz
        dest: /opt         
    
    - name: extract maven package
      unarchive: 
        src: /opt/apache-maven-3.9.12-bin.tar.gz
        dest: /opt
        remote_src: yes

    - name: install git
      yum: 
        name: git
        state: present
      tags: install_git

    - name: check git version
      shell: git --version
      tags: install_git
      register: git_version
    
    - name: print git version
      debug: 
        msg: "{{ git_version.stdout }}"
      tags: install_git
        
    - name: install docker
      yum:
        name: docker
        state: present
      tags: install_docker

    - name: start and enabled docker service
      service:
        name: docker
        state: started
      tags: install_docker

    - name: Verify Docker service status explicitly
      command: systemctl is-active docker
      register: docker_status
      tags: install_docker
 
    - name: Display Docker service status
      debug:
      msg: "Docker service is {{ docker_status.stdout }}"
      tags: install_docker