---
- name:  install jenkins of amazon linux 
  hosts: jenkins-master
  become: true
  tasks: 
    - name: install java 21 
      yum: 
        name: java-21-amazon-corretto
        state: present
    
    - name: add jensins repository 
      get_url: 
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
      
    - name: import jensins gpg key
      command: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    
    - name: install jenkins
      yum: 
        name: jenkins
        state: present

    - name: enable and jenkins service 
      systemd: 
        name: jenkins
        enabled: yes 
        state: started

    - name: enable jenkins to start at boot time
      service: 
        name: jenkins
        enabled: yes

    - name: install git
      yum: 
        name: git
        state: present
      tags: install_git

    - name: check git version
      shell: git --version
      tags: install_git
      register: git_version
    
    - name: print git version
      debug: 
        msg: "{{ git_version.stdout }}"
      tags: install_git
        
