---
- name: setup jenkins slave  
  hosts: jenkins-slave
  tasks:

    - name: Download kubectl binary
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
      tags: install_kubectl

    - name: Verify kubectl version
      ansible.builtin.command: kubectl version --client --short
      register: kubectl_version
      changed_when: false
      tags: install_kubectl

    - name: Show kubectl version
      ansible.builtin.debug:
        msg: "kubectl version: {{ kubectl_version.stdout }}"
      tags: install_kubectl
